USE mysite;

CREATE TABLE IF NOT EXISTS Projects(
	project_id INT PRIMARY KEY AUTO_INCREMENT,
	project_name VARCHAR(100) DEFAULT "",
	project_tag VARCHAR(50) DEFAULT "",
	project_time TIMESTAMP NOT NULL,
	img_url VARCHAR(255) DEFAULT "",
	content TEXT DEFAULT ""
);

CREATE TABLE IF NOT EXISTS Posts(
	PostID INT PRIMARY KEY AUTO_INCREMENT,
	Time TIMESTAMP NOT NULL,
	Title VARCHAR(255) NOT NULL,
	Content TEXT DEFAULT ""
);

CREATE TABLE IF NOT EXISTS Test(
	testID INT PRIMARY KEY AUTO_INCREMENT,
	time TIMESTAMP NOT NULL,
	string VARCHAR(16) NOT NULL,
	string2 TEXT DEFAULT ""
);
